name: ahorcado
version: 0.1.0.0
description: Juego del Ahorcado en Haskell
dependencies:
  - base >= 4.7 && < 5
  - directory
  - process

executables:
  ahorcado:
    main: src/ahorcado.hs
    source-dirs: src 